# Generated by Django 5.2.17 on 2026-09-09 06:31

import django.db.models.deletion
import messenger.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='group', max_length=10)),
                ('key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=4000)),
                ('attachment', models.FileField(blank=True, upload_to=messenger.models.attachment_path)),
                ('filename', models.CharField(blank=True, max_length=200)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('request_key', models.UUIDField(default=uuid.uuid4)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('change_seq', models.PositiveBigIntegerField(default=0)),
                ('legacy_id', models.PositiveBigIntegerField(null=True, unique=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'change_seq'], name='chat_room_changes'), models.Index(fields=['room', 'id'], name='chat_room_history')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'request_key'), name='chat_idempotent_send')],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('muted', models.BooleanField(default=False)),
                ('last_read_id', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messenger.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='chat_unique_member')],
            },
        ),
    ]
