# Generated by Django 5.2.17 on 2026-09-08 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_material_attachment_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('elapsed_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('verdict', models.CharField(choices=[('unknown', 'Нет данных'), ('positive', 'Без срабатываний'), ('negative', 'Требует проверки')], default='unknown', max_length=12)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('rule_version', models.CharField(blank=True, max_length=30)),
                ('comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('imported', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='block_progress', to='courses.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('unknown', 'Нет данных'), ('positive', 'Без срабатываний'), ('negative', 'Требует проверки')], max_length=12)),
                ('note', models.TextField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='learning.blockprogress')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='blockprogress',
            index=models.Index(fields=['user', 'completed_at'], name='block_user_completed'),
        ),
        migrations.AddConstraint(
            model_name='blockprogress',
            constraint=models.UniqueConstraint(fields=('user', 'material'), name='unique_user_block'),
        ),
    ]
