# Generated by Django 5.2.17 on 2026-09-08 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_preserve_quiz_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='attachment_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.material'),
        ),
    ]
