# Generated by Django 5.2.17 on 2026-09-07 19:09

import django.db.models.deletion
import studio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_course_is_listed_material_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый курс', max_length=180)),
                ('data', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('published_revision', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='courses.course')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studio_source', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=studio.models.asset_path)),
                ('name', models.CharField(max_length=240)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.draft')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cover', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.asset')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'course'), name='unique_release_asset')],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='studio_release', to='courses.course')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='studio.draft')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draft', 'number'), name='unique_studio_release_number')],
            },
        ),
    ]
