# Generated by Django 5.2.17 on 2026-09-10 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_material_attachment_of'),
        ('studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLease',
            fields=[
                ('name', models.CharField(default='autoquiz', max_length=32, primary_key=True, serialize=False)),
                ('token', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_key', models.CharField(max_length=40)),
                ('fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('queued', 'В очереди'), ('transcribing', 'Распознаём речь'), ('generating', 'Составляем вопросы'), ('ready', 'Ожидает проверки'), ('failed', 'Нужна помощь'), ('cancelled', 'Отменено'), ('stale', 'Видео заменено'), ('applied', 'Тест добавлен')], db_index=True, default='queued', max_length=20)),
                ('phase', models.CharField(blank=True, max_length=240)),
                ('error', models.TextField(blank=True)),
                ('language', models.CharField(default='ru', max_length=5)),
                ('model', models.CharField(max_length=120)),
                ('whisper_model', models.CharField(default='medium', max_length=40)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('replace_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('reviewed_revision', models.PositiveIntegerField(default=0)),
                ('token', models.UUIDField(blank=True, null=True)),
                ('quiz_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_generations', to='studio.draft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=40)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('quote', models.TextField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_sources', to='autoquiz.generation')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('quote', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_source', to='courses.question')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_sources', to='courses.material')),
            ],
        ),
        migrations.AddConstraint(
            model_name='generation',
            constraint=models.UniqueConstraint(fields=('draft', 'video_key', 'fingerprint'), name='unique_video_quiz_input'),
        ),
        migrations.AddConstraint(
            model_name='draftsource',
            constraint=models.UniqueConstraint(fields=('generation', 'question_key'), name='unique_draft_question_source'),
        ),
    ]
