# Generated by Django 5.2.17 on 2026-09-08 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_material_attachment_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('heartbeat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
                ('starter', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('tests', models.JSONField(default=list)),
                ('time_limit', models.PositiveSmallIntegerField(default=2)),
                ('memory_limit', models.PositiveSmallIntegerField(default=128)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_task', to='courses.material')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='check', max_length=10)),
                ('code', models.TextField()),
                ('stdin', models.TextField(blank=True)),
                ('request_key', models.UUIDField()),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('claim_token', models.UUIDField(null=True)),
                ('diagnostic', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('passed_tests', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practice.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='unique_submission_request')],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('stdin', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('video_position', models.FloatField(default=0)),
                ('video_revision', models.PositiveIntegerField(default=0)),
                ('touched_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'material'), name='unique_learning_workspace')],
            },
        ),
    ]
