# Generated by Django 5.2.17 on 2026-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='retry_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='task_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
